version: '3'
networks:
  net:
services:
  jenkins:
    container_name: jenkins
    image: victorgrubio/jenkins_course_zero_hero:jenkins-pipelines-docker
    build:
      context: pipelines
    ports:
      - "8082:8080"
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
      - $PWD/jenkins-ansible/ansible:/var/jenkins_home/ansible
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - net
  remote_host:
    container_name: remote_host
    image: victorgrubio/jenkins_course_zero_hero:remote-host
    build:
      context: centos7
    volumes:
      - $PWD/aws-s3.sh:/tmp/script.sh
    networks:
      - net
  db_host:
    container_name: db
    image: mysql:5.7
    restart: always
    environment:
      - "MYSQL_ROOT_PASSWORD=1234"
      - "MYSQL_DATABASE=people"
    volumes:
      - $PWD/db_backup/jenkins_dump.sql:/docker-entrypoint-initdb.d/jenkins_dump.sql
    networks:
      - net
    ports:
      - "3307:3306"
  web:
    container_name: web
    image: victorgrubio/jenkins_course_zero_hero:php-webserver
    build:
      context: web
    ports:
      - "8000:80"
    networks:
      - net