pipeline{
    agent any
    stages {
        stage('Build'){
            steps {
                sh  """
                    ./jenkins/build/mvn.sh mvn -B -DskiptTests clean package
                    ./jenkins/build/build.sh
                    """
            }
        }
        stage('Test'){
            steps {
                sh  """
                    ./jenkins/test/mvn.sh mvn test
                    """
            }
        }
        stage('Push'){
            steps {
            
            }
        }
        stage('Deploy'){
            steps {
            
            }
        }
    }
}