FROM ubuntu:18.04
RUN apt-get update && apt-get install -y openssh-server && \
    useradd remote_user && \
    echo "remote_user:1234" | chpasswd && \
    mkdir /home/remote_user/.ssh && \
    chmod 700 /home/remote_user/.ssh  && \
    mkdir -p -m0755 /var/run/sshd

COPY jenkins_course_key.pub /home/remote_user/.ssh/authorized_keys

RUN chown remote_user:remote_user -R /home/remote_user && \
    chmod 400 /home/remote_user/.ssh/authorized_keys && \
    ssh-keygen -A && rm -rf /run/nologin

ENTRYPOINT ["/usr/sbin/sshd", "-D"]