FROM centos:8
RUN yum -y install openssh-server && \
    useradd remote_user && \
    echo "remote_user:1234" | chpasswd && \
    mkdir /home/remote_user/.ssh && \
    chmod 700 /home/remote_user/.ssh 

COPY jenkins_course_key.pub /home/remote_user/.ssh/authorized_keys

RUN chown remote_user:remote_user -R /home/remote_user && \
    chmod 400 /home/remote_user/.ssh/authorized_keys && \
    ssh-keygen -A && rm -rf /run/nologin

ENTRYPOINT ["/usr/sbin/sshd", "-D"]